### ISSUE TITLE
pop!OS 22.04 LTS x64  File "/.../tasmotizer.py", line 8, in <module> - import tasmotizer_esptool as esptool"

### ISSUE THREAD

**Issue by BSDf-dasHaus** [tasmota/tasmotizer#128]
File "/.../tasmotizer.py", line 8, in <module> - import tasmotizer_esptool as esptool"

i was a blisfully mindless little tasmotizer-er and performed a dist-upgrade under pop!OS and voila...busted.

dragged out the original install process, reran and nope...still busted.

full error reported
---
Traceback (most recent call last):
  File "/fullPathTo/tasmotizer/tasmotizer.py", line 8, in <module>
    import tasmotizer_esptool as esptool
  File "/fullPathTo/tasmotizer/tasmotizer_esptool.py", line 36, in <module>
    from PyQt5.QtCore import pyqtSignal, QObject, pyqtSlot
ImportError: /usr/local/lib/python3.10/dist-packages/PyQt5-5.15.6-py3.10-linux-x86_64.egg/PyQt5/QtCore.abi3.so: undefined symbol: _ZdlPvm, version Qt_5

**Comment by Jason2866** [comment]
Which python version are you using?
