### ISSUE TITLE
OSX issue

### ISSUE THREAD

**Issue by podarok** [tasmota/tasmotizer#46]
![image](https://user-images.githubusercontent.com/563412/87671706-71f46100-c77a-11ea-993d-c110ec3acc44.png)

```
sudo tasmotizer.py
esptool.py v2.8
Serial port /dev/tty.usbserial-14610
Traceback (most recent call last):
  File "/usr/local/bin/tasmotizer.py", line 86, in execute
    esptool.main(command)
  File "/usr/local/lib/python3.8/site-packages/tasmotizer_esptool.py", line 2930, in main
    esp = chip_class(each_port, initial_baud, args.trace)
  File "/usr/local/lib/python3.8/site-packages/tasmotizer_esptool.py", line 268, in __init__
    self._port = serial.serial_for_url(port)
  File "/usr/local/lib/python3.8/site-packages/serial/__init__.py", line 88, in serial_for_url
    instance.open()
  File "/usr/local/lib/python3.8/site-packages/serial/serialposix.py", line 272, in open
    self._reconfigure_port(force_update=True)
  File "/usr/local/lib/python3.8/site-packages/serial/serialposix.py", line 435, in _reconfigure_port
    termios.tcsetattr(
termios.error: (22, 'Invalid argument')
Abort trap: 6

```
When trying to Flash

**Comment by podarok** [comment]
Tested latest master
```
python ./tasmotizer.py
esptool.py v2.8
Serial port /dev/tty.usbserial-14610
Traceback (most recent call last):
  File "./tasmotizer.py", line 86, in execute
    esptool.main(command)
  File "/private/var/www/tasmotizer/tasmotizer_esptool.py", line 2930, in main
    esp = chip_class(each_port, initial_baud, args.trace)
  File "/private/var/www/tasmotizer/tasmotizer_esptool.py", line 268, in __init__
    self._port = serial.serial_for_url(port)
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/serial/__init__.py", line 88, in serial_for_url
    instance.open()
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/serial/serialposix.py", line 272, in open
    self._reconfigure_port(force_update=True)
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/serial/serialposix.py", line 435, in _reconfigure_port
    termios.tcsetattr(
termios.error: (22, 'Invalid argument')
Abort trap: 6
```
same issue

![image](https://user-images.githubusercontent.com/563412/87672104-15de0c80-c77b-11ea-9097-edd97a84af2c.png)

**Comment by podarok** [comment]
```
pip3 install PyQt5 pyserial
Requirement already satisfied: PyQt5 in /usr/local/lib/python3.8/site-packages (5.15.0)
Requirement already satisfied: pyserial in /usr/local/lib/python3.8/site-packages (3.4)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /usr/local/lib/python3.8/site-packages (from PyQt5) (12.8.0)
```

**Comment by raenrfm** [comment]
Not sure if it's related to your issue but seems like it, I get this with Linux Mint 20:

Traceback (most recent call last):
  File "tasmotizer.py", line 15, in <module>
    from PyQt5.QtSerialPort import QSerialPortInfo, QSerialPort
ModuleNotFoundError: No module named 'PyQt5.QtSerialPort'

I also have all the requirements satisfied.

**Comment by thomo** [comment]
Same using High Sierra - when selecting checkbox "Release" or "Development" it crashes. I then check if I can reach "`thehackbox.org`" in the browser - and it can't be resolved. 

Whatever the reason, it should be so that if `http://thehackbox.org/tasmota/release/release.php` / `http://thehackbox.org/tasmota/development.php` are not available, appropriate error handling is done.

Tasmotizer 1.0
PyQt5 5.15.0
macOS 10.13.6

**Comment by Jason2866** [comment]
Please use version 1.1c the OTA source has changed

**Comment by thomo** [comment]
I rechecked it (with 1.0) after thehackbox.org is reachable again - and it work now as expected.
